### PR TITLE
Is Travis CI still running on this project?

### PR DESCRIPTION
**Pull request by cclauss**
Given that Travis CI seems to be on vacation, can we please switch this sample over to GitHub Actions?
* https://travis-ci.org/github/pyinstaller
* https://travis-ci.com/github/pyinstaller

### CODE REVIEW

**Comment by bwoodsend** [comment]
We're already validating this package on PyInstaller's own CI ([here](https://github.com/pyinstaller/pyinstaller/blob/4b47eda847cb7a064f8c35a79b483bba3cf500ca/.github/workflows/ci.yml#L127)) and we haven't had any reason to touch this repo for ages so to be honest we might as well just scrap the workflow unless we intend to rejiggle this sample project in the future. Otherwise, yes, Github Actions would be best.

**Comment by Legorooj** [comment]
I'm just going to scrap the workflow here. We can always re-add it later.

**Comment by cclauss** [comment]
What would be really cool would be if the pyinstaller project had a default GitHub Action like:
* https://github.com/codespell-project/actions-codespell
* https://black.readthedocs.io/en/stable/integrations/github_actions.html
* https://github.com/marketplace/actions/pyinstaller-windows
* https://github.com/topics/wine-pyinstaller

I know that making a one-size-fits-all GitHub Action for pyinstaller would be hard work but a sample Action that could build Linux, macOS, and Windows executables and is supported by this community would be a powerful jumpstart for many.

**Comment by Legorooj** [comment]
Writing an official github action to build PyInstaller executables is an idea I'm open to. Please open a feature request on the main repo @cclauss, we can discuss it there.

**Comment by cclauss** [comment]
pyinstaller/pyinstaller#6296

**Pull request closed without merging**
